module Withings::MeasureType
  WEIGHT = 1
  HEIGHT = 4
  FATFREEMASS = 5
  FATRATIO = 6
  FATMASSWEIGHT = 8
  DIASTOLICBLOODPRESSURE = 9
  SYSTOLICBLOODPRESSURE  = 10
  HEARTPULSE = 11
  TEMPERATURE = 12
  SP02 = 54
  BODYTEMPERATURE = 71
  SKINTEMPERATURE  = 73
  MUSCLEMASS = 76
  HYDRATION  = 77
  BONEMASS = 88
  PULSEWAVEVELOCITY = 91
  VO2 = 123
  ATRIALFIBRILLATIONRESULT = 130
  QRSINTERVALDURATION = 135
  PRINTERVALDURATION = 136
  QTINTERVALDURATION = 137
  CORRECTEDQTINTERVALDURATION = 138
  ATRIALFIBRILLATION = 139
  VASCULARAGE = 155
  NERVEHEALTHSCORECONDUCTANCE = 167
  EXTRACELLULARWATER = 168
  INTRACELLULARWATER = 169
  VISCERALFAT = 170
  FATMASS = 174
  # Not sure why this is different from the other MUSCLEMASS above
  # MUSCLEMASS = 175
  ELECTRODERMALACTIVITY = 196
end
